name: tcpdump
version: "rolling"

architectures:
  - x86_64

categories:
  - sniffing spoofing

build:
  kind: neurodocker
  base-image: kalilinux/kali-rolling:latest
  pkg-manager: apt
  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive
    - install:
        - ca-certificates
        - tcpdump
    - run:
        - command -v tcpdump
        - apt-get clean
        - rm -rf /var/lib/apt/lists/*

deploy:
  bins:
    - tcpdump

readme: |
  ## tcpdump/{{ context.version }}

  Command-line packet analyzer from Kali Linux.

